### ISSUE TITLE
Bailo Helm Install 

### ISSUE THREAD

**Issue by ConnalATU** [gchq/Bailo#1168]
Hello, Im facing an auth issues when installing bailo with helm, everything is running but an auth issue with the backend. 

Gives auth error when connecting to mongoDB, have all the secret keys in place, host is also correct.

Any ideas?

**Comment by ARADDCC013** [comment]
I am not able to replicate this issues with our current main whilst deploying to K8s. Assuming certs were created as per https://github.com/gchq/Bailo/tree/main/infrastructure/helm and helm deployment worked without error, could you please post the error. 
Environment variable MONGO_CONNECTION_URI in backed can be used to connect to mongodb which is managed by _helper.tpl https://github.com/gchq/Bailo/blob/main/infrastructure/helm/bailo/templates/_helpers.tpl. You can try connecting to bailo-mongodb* service from your localhost or shell into bailo-mongodb* pod and use `mongosh <MONGO_CONNECTION_URI>` to ensure mongodb is set correctly.

Thank you

**Comment by ConnalATU** [comment]
Thanks for the reply, have updated the bailo-deployment.yaml file in the helm chart to use MONGO_PASSWORD - in the connection string just the key was being sent but not the value.

**Comment by a3957273** [comment]
Hey @ConnalATU, we've tried to make some changes to hopefully improve this.  As part of #1173 we've split up the config so that instead of just:

```
uri: 'mongodb://username:password@host/database
```

It's now split into:

```
uri: 'mongodb://host/database',
user: 'username',
pass: 'password'
```

This eliminates the complex templating we were doing before, which might have been what was causing you problems?  Would you be able to verify that this fixes the issues you were seeing? :)

**Comment by ConnalATU** [comment]
Thanks for this, i cant test this out at the moment but will in the very near future.

**Comment by a3957273** [comment]
Going to close this for now then!
