### ISSUE TITLE
502 bad gateway when navigating to localhost

### ISSUE THREAD

**Issue by Notabot123** [gchq/Bailo#1584]
Hi. I recently tried instructions from docs as standalone, and also as development install.
docker build -t "bailo:standalone" -f ./Dockerfile.standalone .
docker run --name bailo -p 8080:8080 -d bailo:standalone
The app docker builds and docker runs fine. I can see it in docker desktop for windows. 
When I try to navigate to localhost:8080 however, I receive "502 bad gateway nginx/1.18.0 (Ubuntu)". 
I tried looking online for similar issues people have with nginx and have tried:
- turning off firewall temporarily
- using incognito mode
- swapping 'localhost' for 127.0.0.1 or 0.0.0.0 for upstream in /Bailo-main/infrastructure/standalone/nginx.conf
- adding trailing / to proxy_pass within /Bailo-main/infrastructure/standalonenginx.conf
**Apols if I'm being daft.** Grateful for any feedback/advice.

**Comment by Notabot123** [comment]
I've just redownloaded the entire project, to try again afresh.
Standalone still returns bad gateway. 
Considering the 'npm run certs' recommended for development version....
The certs file already exists such that run certs gives an error.
It contains a file san.cnf (_though not yet certs/key_) 
-p doesn't exist prior to run certs command. Powershell output below:

\Bailo-secondattempt\Bailo-main> npm run certs

> bailo@0.4.0 certs
> npm --prefix ./backend/ run certs
> certs
> mkdir -p certs && openssl genrsa -out certs/key.pem 2048 && openssl req -new -x509 -key certs/key.pem -out certs/cert.pem -config certs/san.cnf -extensions 'v3_req' -days 360 && tsx src/scripts/generateJWKS.ts

A subdirectory or file certs already exists.
Error occurred while processing: certs.

**Comment by ARADDCC013** [comment]
Hi [Notabot123](https://github.com/Notabot123),
This looks to be a problem with our current version of NextJS, where frontend is binding to shared docker eth rather than localhost.
Could you please add:
`ENV HOSTNAME 0.0.0.0`
[Here](https://github.com/gchq/Bailo/blob/e2bdeb3f057eae151480aa17f8940052649b89f7/Dockerfile.standalone#L84)
Will add it to future PR. Thank you for bringing this to our attention.

**Comment by Notabot123** [comment]
I can confirm this now works for me in standalone: **many thanks.**

**Comment by ARADDCC002** [comment]
Fixed in #1587
