### ISSUE TITLE
Supporting custom schema for upload

### ISSUE THREAD

**Issue by dudeperf3ct** [gchq/Bailo#170]
There is no [documentation](https://github.com/gchq/Bailo/blob/main/docs/user-guide.md) around how to create a custom schema (for upload and deployment) in Bailo.

From what I gather perusing through the code, there are example [upload](https://github.com/gchq/Bailo/blob/main/server/scripts/example_schemas/minimal_upload_schema.json) and [deployment](https://github.com/gchq/Bailo/blob/main/server/scripts/example_schemas/minimal_deployment_schema.json) json schemas inside [example_schemas](https://github.com/gchq/Bailo/tree/main/server/scripts/example_schemas) folder that are used as default.

The repo does mention a way

> Some example schemas are installed by default. More schemas can be added by altering and running the addDeploymentSchema.ts and addUploadSchema.ts files.

```bash
ts-node --project tsconfig.server.json server/scripts/addDeploymentSchema.ts
ts-node --project tsconfig.server.json server/scripts/addUploadSchema.ts
```

There are [various references](https://github.com/gchq/Bailo/search?q=highLevelDetails) pointing to example schema being tightly coupled with front-end (written using typescript).

Is there a way to add new fields or keys to model cards in the json schema? Will the front-end reflect the changes automatically?

**Comment by ARADDCC002** [comment]
I'm going to reopen this actually, as the documentation hasn't been added. I think it might be worth considering having a form somewhere for admins to upload/edit schemas as well.

**Comment by a3957273** [comment]
It should be noted that all our schemas use `JsonSchema`, document for which can be found [here](https://json-schema.org/).  As long as you start with the minimal schema, you should be able to add to it as you see fit!

**Comment by ARADDCC002** [comment]
Closing this as we have updated our in-app documentation in #202 under the "administration" section. Feel free to open a new issue if anything isn't clear or if anything is missing.
