### ISSUE TITLE
BAI-22 Support uploading '.tar.gz' files to /upload

### ISSUE THREAD

**Issue by a3957273** [gchq/Bailo#47]
A user should be able to upload a .tar.gz file and receive a built image, in the same way as uploading the same .zip file.  The program should automatically determine whether the file is a .tar.gz or a .zip file and unpack it as specified.

To complete this:
  - The UI should accept files other than .zip (`src/UploadFlow/UploadFile.tsx` & `src/common/FormFlow/FormFlow.tsx`)
  - `server/routes/v1/upload.ts` should accept `.tar.gz` files.
  - `server/utils/build.ts` should be able to unzip `.tar.gz` files.

You can use the default `zlib` library to uncompress, and `tar-stream` to parse the tar file.

**Comment by shawshankkumar** [comment]
Hi, can I have a go at this?

**Comment by a3957273** [comment]
Ah, sorry @shawshankkumar, didn't see your message here.  :(
