### ISSUE TITLE
BAI-133 Investigate why additional fields are not being deleted from boolean questions

### ISSUE THREAD

**Issue by ARADDCC002** [gchq/Bailo#59]
### Subject of the issue

When you select "yes" on a boolean question in the upload/deployment forms, if there's a dependency it will sometimes append an additional question (usually a text field prompting users to explain why they selected "yes") object. If you then change your answer to "no", the formData will keep the additional text object, meaning it causes validation issues. These have been band-aid fixed for now so that the validator ignores dependency errors, but we need to find out if we can remove the additional question objects completely from the form data if the user selects "no".

### Steps to reproduce

* Select "Yes" on any boolean question that has a dependency
* Enter a value in the dependency question field that appears (usually a text field)
* Change "Yes" to "No"in the parent question field

### Expected behaviour

The dependency question should disappear from the form and the object removed from the form data

### Actual behaviour

The dependency question disappears from the form, but the answer entered still exists in the form's data.

**Comment by a3957273** [comment]
Fixed by #60
