### ISSUE TITLE
Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

### ISSUE THREAD

**Issue by stuartjohnstone1978** [gchq/Bailo#863]
### Subject of the issue

When running the docker-compose up command everything builds correctly but the bailio-regiustry service will not start and I get the following error:  

Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

From some research on the internet it appears that when running on a Mac, port 5000 is used for Airplay by default.  

Do you have any suggestions or are you able to provide a docker-compose script that uses an alternate port for the registry service?

### Your environment
Apple Macbook Pro 
M1 Pro

Completely fresh install of Docker, no other containers running.

- version / commit hash of bailo (`git rev-parse HEAD`)
- runtime environment (`docker-compose`, `openshift`)

### Steps to reproduce

Follow the instructions on the GitHub page to run in docker

### Expected behaviour
Bailio should run as expected

### Actual behaviour
Error as above

**Comment by a3957273** [comment]
Given that requests to the registry are typically proxied through `nginx` anyway, you should be able to just remove the exported port without any adverse effects.

Removing the following two lines from [`docker-compose.yml` ](https://github.com/gchq/Bailo/blob/main/docker-compose.yml#L40-L41) (lines 40 and 41) should fix it:

```
    ports:
      - 5000:5000
```



If you still want the port to be exposed, you'll want to change the first value, e.g.:

```
  ports:
    - 5001:5000
```

**Comment by a3957273** [comment]
Looks like people got pretty mad two years ago when Apple took port 5000!

https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/

**Comment by a3957273** [comment]
We're going to close this ticket, hope we've solved it for you.

**Comment by IR96334** [comment]
I have no idea why its saying this
